
data_source : C:\Users\Sneha\Downloads\winequality-red.csv

artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  split_data_dir: split_data_dir
  train_data : train.csv
  test_data : test.csv

  model_dir: model_dir
  model_file: elastiNet.md